# =============================================================================
#  HELIX LANGUAGES
# =============================================================================

# --- Web & Scripts ---
[[language]]
name = "javascript"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "typescript"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "tsx"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "html"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "css"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "lua"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "yaml"
indent = { tab-width = 2, unit = "  " }

# --- Go, Assembly & Make ---
[[language]]
name = "go"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "nasm"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "make"
indent = { tab-width = 4, unit = "\t" }

# --- Systems & Python ---
[[language]]
name = "python"
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "rust"
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "c"
indent = { tab-width = 4, unit = "  " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "  " }
